version: '3'
services: 
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: wasdwasd1
            MYSQL_DATABASE: wt_schema

    admin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: wasdwasd1
            PMA_HOST: db
            PMA_PORT: 3306
        links:
            - db:db
        ports:
            - 3000:80
    backend:
        image: stiviik/hsro-wt-project/backend
        restart: always
        links:
            - db:DATABASE
        ports:
            - 9000:9000
    frontend:
        image: stiviik/hsro-wt-project/frontend
        ports:
            - 4200:80